name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npm jest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Analyze Code with SonarQube
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      - name: Run Cypress Tests
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --config-file cypress.config.js --ci-build-id "Cypress Tests - ${{ github.run_id }}" --parallel

      - name: Upload Cypress Test Results
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          key: ${{ secrets.CYPRESS_RECORD_KEY }}
          command-prefix: "npx cypress run --record --key"
          extra-config: "--verbose"
